name: run transformations
on:
  workflow_dispatch:
    inputs:
      media_type:
        required: true
        type: string
      cloudinary_url:
        required: true
        type: string
      post_id:
        required: true
        type: string

jobs:
  Transform-media:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: Chattinga/Chattinga
          token: ${{ secrets.TK }}

      - name: Install ffmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Running heavy process Here
        run: |
          chmod +x work.sh
          ./work.sh "${{ inputs.post_id }},${{ inputs.media_type }},${{ inputs.cloudinary_url }}" ${{ github.run_number }} >> log.txt 2>&1 || true
        env:
          GH_TOKEN: ${{ secrets.TK }}

      - name: commit logs
        run: |
          mkdir log
          cd log
          gh repo clone John4650-hub/Pastebin
          mv ../log.txt Pastebin
          cd Pastebin
          git config --global user.name "$GIT_USERNAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git add .
          git commit -m "logs from building react aoo"
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
          GIT_AUTHOR_EMAIL: johndelvin51@gmail.com
          GIT_USERNAME: john4650-hub

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TK }}
          repository: john4650-hub/Pastebin
          directory: log/Pastebin

